### ISSUE TITLE
Information about smart servo motors

### ISSUE THREAD

**Issue by metanav** [arduino-libraries/Arduino_Braccio_plusplus#81]
I am trying to drive the Braccio++ using ROS2. I need following information for the URDF.

1. Maximum motor speed  (velocity in m/s)
2. Maximum motor torque (effort in N-m)

How can we get speed at runtime? Is there a method to get/set acceleration?
Also, the speed function parameter is time (ms ?) not the speed (rad/s). 
Where can I find the datasheet for the smart servos?

**Comment by per1234** [comment]
>Where can I find the datasheet for the smart servos?

Hi @metanav. This issue tracker is only used for bug reports or feature requests related to the code or documentation of the "**Arduino_Braccio_plusplus**" library.

Issues about the documentation for the [**Arduino Braccio ++**](https://store.arduino.cc/products/braccioplusplus) hardware should be submitted here:

https://github.com/arduino/docs-content/issues

**Comment by metanav** [comment]
Thanks @per1234, I am closing this and will create a new issue at https://github.com/arduino/docs-content/issues.

**Comment by per1234** [comment]
You are welcome.

To be clear, my previous comment was only addressing the specific part of the issue I quoted. If you have identified bugs or possible enhancements to the content stored in this repository, that is certainly appropriate for this issue tracker.

But in the case of things missing from [the hardware documentation](https://docs.arduino.cc/hardware/braccio-carrier), your report at https://github.com/arduino/docs-content/issues/495 will definitely be the effective approach.

Regards, Per
