### ISSUE TITLE
Servo motors disconnecting while fetching positions

### ISSUE THREAD

**Issue by metanav** [arduino-libraries/Arduino_Braccio_plusplus#91]
It seems that the Nano RP2040 Connect's UART1_TX (GPIO8) is connected to the RST_485/RE(Receiver enable). Also, the same pin GPIO8 is connected to the onboard WiFi UART pin. Although I am not using WiFi in my code but I am investigating this because the servo motors get disconnected/reconnected intermittently while continuously fetching all joints angles (at 10Hz) using the` Braccio.positions() ` method. I am not sure if this is causing the issue. Interestingly a basic example does not have disconnection issue but using multiple Mbed threads with microROS have such kind of behavior. I can see 2 or 3 LEDs (out of 6) in random order changing from green to red to green attached to the motors on the carrier board. Can we change the RST_485/RE connection to another available pin or is it hard-wired?

**Comment by aentinger** [comment]
Hi @metanav :coffee: :wave:

Thank you very much for your comment. However, I believe you've mistaken reading the schematics. **nRE = RST_485 = D8 = GPIO20**. The WiFi UART pin is the literal pin **GPIO8**.

![nano-rp2040](https://user-images.githubusercontent.com/3931733/187840958-879fe03f-7ee8-42bb-a58c-557a0bff36f4.png)

>multiple Mbed threads

could indeed be causing such an issue. If you were willing to share the code I could take a look at it.

**Comment by metanav** [comment]
Hi @aentinger,

Late night schematic reading has never been fruitful. My bad! 

Also, you are right that the Mbed threads were causing the issue. They were running continuously so I've added some delay() and there is no disconnection after that. Though I get some invalid angle reading once or twice in 10 readings/second. Not a big deal, I can ignore them but was wondering that the invalid  position is always 
equal to 5160.880859 for any motors.  I am closing this issue and will reopen if I find any similar issue again.
